# Generated by Django 6.0.7 on 2026-07-28 23:05

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_purok',
            field=models.CharField(blank=True, help_text='Purok this user is responsible for. Currently only meaningful for Barangay Healthworkers, whose Vulnerability_Indicators edit access is restricted to households in this purok.', max_length=50, null=True),
        ),
    ]
