# Generated by Django 6.0.7 on 2026-07-28 05:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('household_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('household_number', models.CharField(max_length=20, unique=True)),
                ('head_of_family', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('purok', models.CharField(max_length=50)),
                ('total_members', models.IntegerField()),
                ('evacuation_priority', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('priority_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='households', to='core.barangay')),
                ('encoded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='households_encoded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'households',
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('member_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('relationship', models.CharField(max_length=50)),
                ('is_senior_citizen', models.BooleanField(default=False)),
                ('is_pwd', models.BooleanField(default=False)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('is_child', models.BooleanField(default=False)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='households.household')),
            ],
            options={
                'db_table': 'household_members',
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityIndicator',
            fields=[
                ('indicator_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_senior_citizen', models.BooleanField(default=False)),
                ('has_pwd', models.BooleanField(default=False)),
                ('has_pregnant_member', models.BooleanField(default=False)),
                ('has_child', models.BooleanField(default=False)),
                ('house_material', models.CharField(choices=[('Concrete', 'Concrete'), ('Mixed', 'Mixed'), ('Light', 'Light'), ('Salvaged', 'Salvaged')], max_length=20)),
                ('roof_material', models.CharField(choices=[('GI Sheet', 'GI Sheet'), ('Cogon', 'Cogon'), ('Mixed', 'Mixed'), ('Concrete', 'Concrete')], max_length=20)),
                ('hazard_zone', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('flood_prone', models.BooleanField(default=False)),
                ('storm_surge_prone', models.BooleanField(default=False)),
                ('landslide_prone', models.BooleanField(default=False)),
                ('coastal_zone', models.BooleanField(default=False)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('assessed_by', models.ForeignKey(help_text='The BHW who performed this assessment.', on_delete=django.db.models.deletion.PROTECT, related_name='vulnerability_assessments', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerability_indicators', to='households.household')),
            ],
            options={
                'db_table': 'vulnerability_indicators',
            },
        ),
        migrations.AddConstraint(
            model_name='household',
            constraint=models.CheckConstraint(condition=models.Q(('evacuation_priority__in', ['High', 'Medium', 'Low']), ('evacuation_priority__isnull', True), _connector='OR'), name='households_evacuation_priority_valid'),
        ),
        migrations.AddConstraint(
            model_name='household',
            constraint=models.CheckConstraint(condition=models.Q(('total_members__gte', 0)), name='households_total_members_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='householdmember',
            constraint=models.CheckConstraint(condition=models.Q(('sex__in', ['Male', 'Female'])), name='household_members_sex_valid'),
        ),
        migrations.AddConstraint(
            model_name='householdmember',
            constraint=models.CheckConstraint(condition=models.Q(('age__gte', 0)), name='household_members_age_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='vulnerabilityindicator',
            constraint=models.CheckConstraint(condition=models.Q(('house_material__in', ['Concrete', 'Mixed', 'Light', 'Salvaged'])), name='vuln_house_material_valid'),
        ),
        migrations.AddConstraint(
            model_name='vulnerabilityindicator',
            constraint=models.CheckConstraint(condition=models.Q(('roof_material__in', ['GI Sheet', 'Cogon', 'Mixed', 'Concrete'])), name='vuln_roof_material_valid'),
        ),
        migrations.AddConstraint(
            model_name='vulnerabilityindicator',
            constraint=models.CheckConstraint(condition=models.Q(('hazard_zone__in', ['High', 'Medium', 'Low'])), name='vuln_hazard_zone_valid'),
        ),
    ]
