# Generated by Django 6.0.7 on 2026-07-29 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='resident_user',
            field=models.OneToOneField(blank=True, help_text='The Resident account linked to this household. Created by the Barangay Secretary via the "create Resident account" action — there is no public signup flow, so this is only ever set through that controlled path.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_household', to=settings.AUTH_USER_MODEL),
        ),
    ]
