# Generated by Django 6.0.7 on 2026-07-28 05:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacuationCenter',
            fields=[
                ('center_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('capacity', models.IntegerField()),
                ('current_occupancy', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Under Maintenance', 'Under Maintenance')], default='Active', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evacuation_centers', to='core.barangay')),
                ('managed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evacuation_centers_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evacuation_centers',
            },
        ),
        migrations.CreateModel(
            name='EvacuationRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_status', models.CharField(choices=[('Checked-in', 'Checked-in'), ('Departed', 'Departed')], default='Checked-in', max_length=20)),
                ('entered_at', models.DateTimeField()),
                ('has_water', models.BooleanField(default=False)),
                ('has_electricity', models.BooleanField(default=False)),
                ('has_medical', models.BooleanField(default=False)),
                ('has_food', models.BooleanField(default=False)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evacuation_records', to='evacuation_centers.evacuationcenter')),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evacuation_records', to='core.disaster')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evacuation_records', to='households.household')),
            ],
            options={
                'db_table': 'evacuation_records',
            },
        ),
        migrations.AddConstraint(
            model_name='evacuationcenter',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Active', 'Inactive', 'Under Maintenance'])), name='centers_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='evacuationcenter',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 0)), name='centers_capacity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='evacuationcenter',
            constraint=models.CheckConstraint(condition=models.Q(('current_occupancy__gte', 0)), name='centers_occupancy_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='evacuationrecord',
            constraint=models.CheckConstraint(condition=models.Q(('entry_status__in', ['Checked-in', 'Departed'])), name='evac_records_entry_status_valid'),
        ),
    ]
