# Generated by Django 6.0.7 on 2026-08-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationcenter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='evacuation_center_photos/'),
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
