# backend/announcements/serializers.py
from rest_framework import serializers

from .models import Announcement, AnnouncementCategory, SMSLog, SMSNotification


class AnnouncementCategorySerializer(serializers.ModelSerializer):
    class Meta:
        model = AnnouncementCategory
        fields = ['announcement_category_id', 'category']
        read_only_fields = ['announcement_category_id']


class AnnouncementSerializer(serializers.ModelSerializer):
    categories = AnnouncementCategorySerializer(many=True, required=False)

    class Meta:
        model = Announcement
        fields = [
            'announcement_id', 'barangay', 'title', 'body', 'is_public', 'posted_by',
            'published_at', 'expires_at', 'created_at', 'updated_at',
            'is_archived', 'archived_at', 'categories',
        ]
        # posted_by is always server-set from the requesting user. barangay
        # is too, EXCEPT for the MDRRMO Officer (whose own .barangay is None,
        # spanning both) — for them it's a required, explicitly-chosen input,
        # enforced/validated in AnnouncementViewSet._resolve_announcement_barangay,
        # not here. It stays out of read_only_fields so that field can carry
        # client input; every other role's submitted barangay (if any) is
        # still fully discarded and overridden server-side, same as before.
        read_only_fields = [
            'announcement_id', 'posted_by',
            'created_at', 'updated_at', 'is_archived', 'archived_at',
        ]
        extra_kwargs = {'barangay': {'required': False}}

    def create(self, validated_data):
        categories_data = validated_data.pop('categories', [])
        announcement = Announcement.objects.create(**validated_data)
        for cat in categories_data:
            AnnouncementCategory.objects.create(announcement=announcement, **cat)
        return announcement

    def update(self, instance, validated_data):
        categories_data = validated_data.pop('categories', None)
        for attr, value in validated_data.items():
            setattr(instance, attr, value)
        instance.save()
        if categories_data is not None:
            instance.categories.all().delete()
            for cat in categories_data:
                AnnouncementCategory.objects.create(announcement=instance, **cat)
        return instance


class SMSLogSerializer(serializers.ModelSerializer):
    class Meta:
        model = SMSLog
        fields = [
            'log_id', 'sms', 'household', 'contact_number', 'delivery_status',
            'gateway_response', 'sent_at', 'is_archived', 'archived_at',
        ]
        read_only_fields = fields  # entirely system-generated by the authorize action


class SMSNotificationSerializer(serializers.ModelSerializer):
    logs = SMSLogSerializer(many=True, read_only=True)

    class Meta:
        model = SMSNotification
        fields = [
            'sms_id', 'barangay', 'subject', 'message_body', 'recipient_type',
            'total_recipients', 'sent_count', 'failed_count', 'status',
            'initiated_by', 'sent_at', 'created_at', 'is_archived', 'archived_at', 'logs',
        ]
        # Only subject/message_body/recipient_type are ever client-supplied —
        # everything else is computed by the create/authorize actions.
        read_only_fields = [
            'sms_id', 'barangay', 'total_recipients', 'sent_count', 'failed_count',
            'status', 'initiated_by', 'sent_at', 'created_at', 'is_archived', 'archived_at',
        ]


class AuthorizeSMSSerializer(serializers.Serializer):
    """
    Optional explicit recipient list — only meaningful when the staged
    broadcast's recipient_type is 'Custom'. Not stored on the model (the
    schema has no field for it); used transiently to build SMSLog rows.
    """
    household_ids = serializers.ListField(child=serializers.UUIDField(), required=False)