# Generated by Django 6.0.7 on 2026-07-28 05:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('announcement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='core.barangay')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements',
            },
        ),
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('sms_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('message_body', models.TextField()),
                ('recipient_type', models.CharField(choices=[('All', 'All'), ('High Priority', 'High Priority'), ('Medium', 'Medium'), ('Low', 'Low'), ('Custom', 'Custom')], max_length=20)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Partially Sent', 'Partially Sent'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_notifications', to='core.barangay')),
                ('initiated_by', models.ForeignKey(help_text='The BDRRMC Chairperson who authorized this broadcast.', on_delete=django.db.models.deletion.PROTECT, related_name='sms_notifications_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sms_notifications',
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_number', models.CharField(max_length=20)),
                ('delivery_status', models.CharField(choices=[('Delivered', 'Delivered'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('gateway_response', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_logs', to='households.household')),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='announcements.smsnotification')),
            ],
            options={
                'db_table': 'sms_logs',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementCategory',
            fields=[
                ('announcement_category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Advisory', 'Advisory'), ('Alert', 'Alert'), ('Informational', 'Informational'), ('Emergency', 'Emergency')], max_length=20)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='announcements.announcement')),
            ],
            options={
                'db_table': 'announcement_categories',
                'constraints': [models.CheckConstraint(condition=models.Q(('category__in', ['Advisory', 'Alert', 'Informational', 'Emergency'])), name='announcement_category_valid')],
                'unique_together': {('announcement', 'category')},
            },
        ),
        migrations.AddConstraint(
            model_name='smsnotification',
            constraint=models.CheckConstraint(condition=models.Q(('recipient_type__in', ['All', 'High Priority', 'Medium', 'Low', 'Custom'])), name='sms_notif_recipient_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='smsnotification',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Pending', 'Sent', 'Partially Sent', 'Failed'])), name='sms_notif_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='smslog',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_status__in', ['Delivered', 'Failed', 'Pending'])), name='sms_logs_delivery_status_valid'),
        ),
    ]
