# Generated by Django 6.0.7 on 2026-08-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        ('households', '0002_household_resident_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='smslog',
            name='sms_logs_delivery_status_valid',
        ),
        migrations.AlterField(
            model_name='smslog',
            name='delivery_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Failed', 'Failed'), ('Pending', 'Pending'), ('Simulated', 'Simulated')], default='Pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='smslog',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_status__in', ['Delivered', 'Failed', 'Pending', 'Simulated'])), name='sms_logs_delivery_status_valid'),
        ),
    ]
