# Generated by Django 6.0.7 on 2026-09-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_remove_smslog_sms_logs_delivery_status_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcement_images/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
