from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from django.utils import timezone


def build_pdf_report(title, subtitle, headers, rows, generated_by):
    """
    Builds a simple tabular PDF report and returns it as an in-memory
    BytesIO buffer, ready to hand to FileResponse. Nothing is written to disk.

    title: main heading, e.g. "Household Report"
    subtitle: e.g. the barangay name or "All Barangays"
    headers: list of column header strings
    rows: list of row lists (values already stringified/display-ready)
    generated_by: name of the user who requested the report
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        leftMargin=0.5 * inch,
        rightMargin=0.5 * inch,
    )
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph(title, styles['Title']))
    elements.append(Paragraph(subtitle, styles['Heading3']))

    generated_at = timezone.now().strftime('%B %d, %Y %I:%M %p')
    elements.append(
        Paragraph(f'Generated by {generated_by} on {generated_at}', styles['Normal'])
    )
    elements.append(Spacer(1, 0.25 * inch))

    table_data = [headers] + [[str(cell) for cell in row] for row in rows]

    if not rows:
        elements.append(Paragraph('No records found.', styles['Normal']))
    else:
        table = Table(table_data, repeatRows=1)
        table.setStyle(
            TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e6f4c')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cccccc')),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f5f5f5')]),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ])
        )
        elements.append(table)

    doc.build(elements)
    buffer.seek(0)
    return buffer