# Generated by Django 6.0.7 on 2026-07-28 05:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardMap',
            fields=[
                ('map_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('map_title', models.CharField(max_length=255)),
                ('hazard_type', models.CharField(choices=[('Flood', 'Flood'), ('Storm Surge', 'Storm Surge'), ('Landslide', 'Landslide'), ('Earthquake', 'Earthquake')], max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('map_url', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hazard_maps', to='core.barangay')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hazard_maps_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hazard_maps',
                'constraints': [models.CheckConstraint(condition=models.Q(('hazard_type__in', ['Flood', 'Storm Surge', 'Landslide', 'Earthquake'])), name='hazard_maps_type_valid')],
            },
        ),
    ]
