# Generated by Django 6.0.7 on 2026-09-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardmap',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='hazard_map_images/'),
        ),
        migrations.AlterField(
            model_name='hazardmap',
            name='map_url',
            field=models.TextField(blank=True),
        ),
    ]
