# Generated by Django 6.0.7 on 2026-07-28 05:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('barangay_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Barangays',
                'db_table': 'barangay',
            },
        ),
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('disaster_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Flood', 'Flood'), ('Storm Surge', 'Storm Surge'), ('Landslide', 'Landslide'), ('Earthquake', 'Earthquake'), ('Fire', 'Fire'), ('Other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Resolved', 'Resolved')], default='Ongoing', max_length=20)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disasters',
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['Flood', 'Storm Surge', 'Landslide', 'Earthquake', 'Fire', 'Other'])), name='disasters_type_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['Ongoing', 'Resolved'])), name='disasters_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('contact_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('Barangay Secretary', 'Barangay Secretary'), ('MDRRMO Officer', 'MDRRMO Officer'), ('BDRRMC Chairperson', 'BDRRMC Chairperson'), ('Barangay Kagawad/Tanod', 'Barangay Kagawad/Tanod'), ('Barangay Healthworker', 'Barangay Healthworker')], max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_contacts', to='core.barangay')),
            ],
            options={
                'db_table': 'emergency_contacts',
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['Barangay Secretary', 'MDRRMO Officer', 'BDRRMC Chairperson', 'Barangay Kagawad/Tanod', 'Barangay Healthworker'])), name='emergency_contacts_role_valid')],
            },
        ),
    ]
